CREATE TABLE `user` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`user_name` VARCHAR(32) NULL DEFAULT NULL,
	`pass_word` VARCHAR(16) NULL DEFAULT NULL,
	`address` VARCHAR(16) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
